### ISSUE TITLE
Package failed to install in VS2017

### ISSUE THREAD

**Issue by Omcsesz** [Akeloya/WPFComponents#1]
Hello, Yugov!

When I try to install the package to my project, I get the following error:

Could not install package 'WpfExtendedControls 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Can you please help?

**Comment by Akeloya** [comment]
Hi!
<TargetFrameworks>netcoreapp3.1;net48</TargetFrameworks>

**Comment by Akeloya** [comment]
I update package to support .net 4.7.2, and .net 5.
Also I update readme

**Comment by Omcsesz** [comment]
It installs now, we can close this!
